name: bloc_gen
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  dart_style: ^2.3.6
  meta: 1.11.0
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^3.0.0
  test: ^1.24.0
